In [1]:
import pandas as pd

In [8]:
bigmac= pd.read_csv("files/bigmac.csv", parse_dates=["Date"])
bigmac.head()

        Date    Country  Price in US Dollars
0 2016-01-01  Argentina                 2.39
1 2016-01-01  Australia                 3.74
2 2016-01-01     Brazil                 3.35
3 2016-01-01    Britain                 4.22
4 2016-01-01     Canada                 4.14

In [9]:
bigmac.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 652 entries, 0 to 651
Data columns (total 3 columns):
Date                   652 non-null datetime64[ns]
Country                652 non-null object
Price in US Dollars    652 non-null float64
dtypes: datetime64[ns](1), float64(1), object(1)
memory usage: 15.4+ KB

In [13]:
bigmac.set_index(keys=["Date", "Country"], inplace=True)

In [17]:
bigmac.head(3)

                      Price in US Dollars
Date       Country
2010-01-01 Argentina                 1.84
           Australia                 3.98
           Brazil                    4.76

In [16]:
bigmac.sort_index(inplace=True)

In [20]:
type(bigmac.index)

pandas.core.indexes.multi.MultiIndex

In [22]:
bigmac.index[0]

Timestamp('2010-01-01 00:00:00')

In [31]:
bigmac = pd.read_csv("files/bigmac.csv", parse_dates=["Date"], index_col=["Date", "Country"])
bigmac.sort_index(inplace=True)
bigmac.head(3)

                      Price in US Dollars
Date       Country
2010-01-01 Argentina                 1.84
           Australia                 3.98
           Brazil                    4.76

In [26]:
bigmac.index.get_level_values(1)

Index(['Argentina', 'Australia', 'Brazil', 'Britain', 'Canada', 'Chile',
       'China', 'Colombia', 'Costa Rica', 'Czech Republic',
       ...
       'Switzerland', 'Taiwan', 'Thailand', 'Turkey', 'UAE', 'Ukraine',
       'United States', 'Uruguay', 'Venezuela', 'Vietnam'],
      dtype='object', name='Country', length=652)

In [29]:
bigmac.index.set_names(["Date", "Location"], inplace=True)
bigmac.head(3)

                      Price in US Dollars
Date       Location
2010-01-01 Argentina                 1.84
           Australia                 3.98
           Brazil                    4.76

In [30]:
bigmac.sort_index(ascending=[True, False])

                           Price in US Dollars
Date       Location
2010-01-01 Uruguay                        3.32
           United States                  3.58
           Ukraine                        1.83
           UAE                            2.99
           Turkey                         3.83
           Thailand                       2.11
           Taiwan                         2.36
           Switzerland                    6.30
           Sweden                         5.51
           Sri Lanka                      1.83
           South Korea                    2.98
           South Africa                   2.46
           Singapore                      3.19
           Saudi Arabia                   2.67
           Russia                         2.34
           Poland                         2.86
           Philippines                    2.21
           Peru                           2.81
           Pakistan                       2.42
           Norway                         7.02
           New Zealand                    3.61
           Mexico                         2.50
           Malaysia                       2.08
           Lithuania                      2.87
           Latvia                         3.09
           Japan                          3.50
           Israel                         3.99
           Indonesia                      2.24
           Hungary                        3.86
           Hong Kong                      1.91
...                                        ...
2016-01-01 Mexico                         2.81
           Malaysia                       1.82
           Japan                          3.12
           Italy                          4.30
           Israel                         4.29
           Ireland                        4.25
           Indonesia                      2.19
           India                          1.90
           Hungary                        3.08
           Hong Kong                      2.48
           Greece                         3.60
           Germany                        3.86
           France                         4.41
           Finland                        4.41
           Euro area                      4.00
           Estonia                        3.23
           Egypt                          2.16
           Denmark                        4.32
           Czech Republic                 2.98
           Costa Rica                     4.02
           Colombia                       2.43
           China                          2.68
           Chile                          2.94
           Canada                         4.14
           Britain                        4.22
           Brazil                         3.35
           Belgium                        4.25
           Austria                        3.76
           Australia                      3.74
           Argentina                      2.39

[652 rows x 1 columns]

In [40]:
bigmac.loc[("2010-01-01", "Brazil"), "Price in US Dollars"]

4.7599999999999998

In [44]:
bigmac.ix[("2010-01-01", "China"), "Price in US Dollars"]

1.8300000000000001

In [45]:
bigmac.transpose()

Date                2010-01-01                                              \
Country              Argentina Australia Brazil Britain Canada Chile China
Price in US Dollars       1.84      3.98   4.76    3.67   3.97  3.18  1.83

Date                                                     ...    2016-01-01  \
Country             Colombia Costa Rica Czech Republic   ...   Switzerland
Price in US Dollars     3.91       3.52           3.71   ...          6.44

Date                                                                    \
Country             Taiwan Thailand Turkey   UAE Ukraine United States
Price in US Dollars   2.08     3.09   3.41  3.54    1.54          4.93

Date
Country             Uruguay Venezuela Vietnam
Price in US Dollars    3.74      0.66    2.67

[1 rows x 652 columns]

In [50]:
bigmac.swaplevel()

                           Price in US Dollars
Country        Date
Argentina      2010-01-01                 1.84
Australia      2010-01-01                 3.98
Brazil         2010-01-01                 4.76
Britain        2010-01-01                 3.67
Canada         2010-01-01                 3.97
Chile          2010-01-01                 3.18
China          2010-01-01                 1.83
Colombia       2010-01-01                 3.91
Costa Rica     2010-01-01                 3.52
Czech Republic 2010-01-01                 3.71
Denmark        2010-01-01                 5.99
Egypt          2010-01-01                 2.38
Euro area      2010-01-01                 4.84
Hong Kong      2010-01-01                 1.91
Hungary        2010-01-01                 3.86
Indonesia      2010-01-01                 2.24
Israel         2010-01-01                 3.99
Japan          2010-01-01                 3.50
Latvia         2010-01-01                 3.09
Lithuania      2010-01-01                 2.87
Malaysia       2010-01-01                 2.08
Mexico         2010-01-01                 2.50
New Zealand    2010-01-01                 3.61
Norway         2010-01-01                 7.02
Pakistan       2010-01-01                 2.42
Peru           2010-01-01                 2.81
Philippines    2010-01-01                 2.21
Poland         2010-01-01                 2.86
Russia         2010-01-01                 2.34
Saudi Arabia   2010-01-01                 2.67
...                                        ...
Italy          2016-01-01                 4.30
Japan          2016-01-01                 3.12
Malaysia       2016-01-01                 1.82
Mexico         2016-01-01                 2.81
Netherlands    2016-01-01                 3.71
New Zealand    2016-01-01                 3.91
Norway         2016-01-01                 5.21
Pakistan       2016-01-01                 2.86
Peru           2016-01-01                 2.93
Philippines    2016-01-01                 2.79
Poland         2016-01-01                 2.37
Portugal       2016-01-01                 3.23
Russia         2016-01-01                 1.53
Saudi Arabia   2016-01-01                 3.20
Singapore      2016-01-01                 3.27
South Africa   2016-01-01                 1.77
South Korea    2016-01-01                 3.59
Spain          2016-01-01                 3.76
Sri Lanka      2016-01-01                 2.43
Sweden         2016-01-01                 5.23
Switzerland    2016-01-01                 6.44
Taiwan         2016-01-01                 2.08
Thailand       2016-01-01                 3.09
Turkey         2016-01-01                 3.41
UAE            2016-01-01                 3.54
Ukraine        2016-01-01                 1.54
United States  2016-01-01                 4.93
Uruguay        2016-01-01                 3.74
Venezuela      2016-01-01                 0.66
Vietnam        2016-01-01                 2.67

[652 rows x 1 columns]

In [59]:
world = pd.read_csv("files/worldstats.csv", index_col=["country", "year"])
world.head(3)

                  Population           GDP
country    year
Arab World 2015  392022276.0  2.530102e+12
           2014  384222592.0  2.873600e+12
           2013  376504253.0  2.846994e+12

In [55]:
world.stack().to_frame()

                                       0
country    year
Arab World 2015 Population  3.920223e+08
                GDP         2.530102e+12
           2014 Population  3.842226e+08
                GDP         2.873600e+12
           2013 Population  3.765043e+08
                GDP         2.846994e+12
           2012 Population  3.688026e+08
                GDP         2.773270e+12
           2011 Population  3.610318e+08
                GDP         2.497945e+12
           2010 Population  3.531122e+08
                GDP         2.103825e+12
           2009 Population  3.450542e+08
                GDP         1.798878e+12
           2008 Population  3.368865e+08
                GDP         2.081343e+12
           2007 Population  3.287666e+08
                GDP         1.641666e+12
           2006 Population  3.209067e+08
                GDP         1.404190e+12
           2005 Population  3.134309e+08
                GDP         1.184735e+12
           2004 Population  3.063874e+08
                GDP         9.639180e+11
           2003 Population  2.997320e+08
                GDP         8.218702e+11
           2002 Population  2.934026e+08
                GDP         7.279939e+11
           2001 Population  2.872918e+08
                GDP         7.221506e+11
...                                  ...
Zimbabwe   1974 Population  5.967861e+06
                GDP         3.982161e+09
           1973 Population  5.768382e+06
                GDP         3.309354e+09
           1972 Population  5.573312e+06
                GDP         2.677729e+09
           1971 Population  5.385342e+06
                GDP         2.178716e+09
           1970 Population  5.206311e+06
                GDP         1.884206e+09
           1969 Population  5.036321e+06
                GDP         1.747999e+09
           1968 Population  4.874113e+06
                GDP         1.479600e+09
           1967 Population  4.718612e+06
                GDP         1.397002e+09
           1966 Population  4.568320e+06
                GDP         1.281750e+09
           1965 Population  4.422132e+06
                GDP         1.311436e+09
           1964 Population  4.279561e+06
                GDP         1.217138e+09
           1963 Population  4.140804e+06
                GDP         1.159512e+09
           1962 Population  4.006262e+06
                GDP         1.117602e+09
           1961 Population  3.876638e+06
                GDP         1.096647e+09
           1960 Population  3.752390e+06
                GDP         1.052990e+09

[22422 rows x 1 columns]

In [58]:
world.unstack().unstack().unstack()

country           Afghanistan       Albania       Algeria       Andorra  \
           year
Population 1960  8.994793e+06           NaN  1.112489e+07           NaN
           1961  9.164945e+06           NaN  1.140486e+07           NaN
           1962  9.343772e+06           NaN  1.169015e+07           NaN
           1963  9.531555e+06           NaN  1.198513e+07           NaN
           1964  9.728645e+06           NaN  1.229597e+07           NaN
           1965  9.935358e+06           NaN  1.262695e+07           NaN
           1966  1.014884e+07           NaN  1.298027e+07           NaN
           1967  1.036860e+07           NaN  1.335420e+07           NaN
           1968  1.059979e+07           NaN  1.374438e+07           NaN
           1969  1.084951e+07           NaN  1.414444e+07           NaN
           1970  1.112110e+07           NaN  1.455003e+07  2.427900e+04
           1971  1.141282e+07           NaN  1.496011e+07  2.556000e+04
           1972  1.171690e+07           NaN  1.537710e+07  2.689200e+04
           1973  1.202251e+07           NaN  1.580443e+07  2.823100e+04
           1974  1.231555e+07           NaN  1.624711e+07  2.951400e+04
           1975  1.258295e+07           NaN  1.670910e+07  3.070600e+04
           1976  1.283136e+07           NaN  1.719024e+07  3.178100e+04
           1977  1.305650e+07           NaN  1.769018e+07  3.276900e+04
           1978  1.322255e+07           NaN  1.821233e+07  3.374600e+04
           1979  1.328328e+07           NaN  1.876076e+07  3.481900e+04
           1980  1.321141e+07           NaN  1.933772e+07  3.606300e+04
           1981  1.299692e+07           NaN  1.994367e+07  3.750200e+04
           1982           NaN           NaN  2.057570e+07  3.911200e+04
           1983           NaN           NaN  2.122829e+07  4.086200e+04
           1984           NaN  2.904429e+06  2.189386e+07  4.270400e+04
           1985           NaN  2.964762e+06  2.256591e+07  4.459700e+04
           1986           NaN  3.022635e+06  2.324128e+07  4.651500e+04
           1987           NaN  3.083605e+06  2.391789e+07  4.845800e+04
           1988           NaN  3.142336e+06  2.459149e+07  5.043100e+04
           1989           NaN  3.227943e+06  2.525767e+07  5.244900e+04
...                       ...           ...           ...           ...
GDP        1986           NaN  2.173750e+09  6.369630e+10  4.819962e+08
           1987           NaN  2.156625e+09  6.674227e+10  6.113001e+08
           1988           NaN  2.126000e+09  5.908907e+10  7.214260e+08
           1989           NaN  2.335125e+09  5.563149e+10  7.954895e+08
           1990           NaN  2.101625e+09  6.204510e+10  1.028989e+09
           1991           NaN  1.139167e+09  4.571537e+10  1.106891e+09
           1992           NaN  7.094526e+08  4.800330e+10  1.209993e+09
           1993           NaN  1.228071e+09  4.994646e+10  1.007091e+09
           1994           NaN  1.985674e+09  4.254257e+10  1.017545e+09
           1995           NaN  2.424499e+09  4.176405e+10  1.178745e+09
           1996           NaN  3.314898e+09  4.694150e+10  1.224023e+09
           1997           NaN  2.359903e+09  4.817786e+10  1.180646e+09
           1998           NaN  2.707124e+09  4.818775e+10  1.211954e+09
           1999           NaN  3.414761e+09  4.864061e+10  1.239840e+09
           2000           NaN  3.632044e+09  5.479006e+10  1.401694e+09
           2001  2.461666e+09  4.060759e+09  5.474471e+10  1.484005e+09
           2002  4.128818e+09  4.435079e+09  5.676029e+10  1.717564e+09
           2003  4.583649e+09  5.746946e+09  6.786383e+10  2.373836e+09
           2004  5.285462e+09  7.314865e+09  8.532500e+10  2.916913e+09
           2005  6.275076e+09  8.158549e+09  1.031982e+11  3.248135e+09
           2006  7.057598e+09  8.992642e+09  1.170273e+11  3.536452e+09
           2007  9.843842e+09  1.070101e+10  1.349771e+11  4.010785e+09
           2008  1.019053e+10  1.288135e+10  1.710007e+11  4.001349e+09
           2009  1.248694e+10  1.204421e+10  1.372110e+11  3.649863e+09
           2010  1.593680e+10  1.192695e+10  1.612073e+11  3.346317e+09
           2011  1.793024e+10  1.289087e+10  2.000131e+11  3.427236e+09
           2012  2.053654e+10  1.231978e+10  2.090474e+11  3.146178e+09
           2013  2.004633e+10  1.278103e+10  2.097035e+11  3.249101e+09
           2014  2.005019e+10  1.327796e+10  2.135185e+11           NaN
           2015  1.919944e+10  1.145560e+10  1.668386e+11           NaN

country                Angola  Antigua and Barbuda    Arab World  \
           year
Population 1960           NaN                  NaN           NaN
           1961           NaN                  NaN           NaN
           1962           NaN                  NaN           NaN
           1963           NaN                  NaN           NaN
           1964           NaN                  NaN           NaN
           1965           NaN                  NaN           NaN
           1966           NaN                  NaN           NaN
           1967           NaN                  NaN           NaN
           1968           NaN                  NaN  1.155571e+08
           1969           NaN                  NaN  1.188239e+08
           1970           NaN                  NaN  1.221282e+08
           1971           NaN                  NaN  1.254391e+08
           1972           NaN                  NaN  1.288012e+08
           1973           NaN                  NaN  1.322990e+08
           1974           NaN                  NaN  1.360445e+08
           1975           NaN                  NaN  1.401144e+08
           1976           NaN                  NaN  1.445420e+08
           1977           NaN         7.022300e+04  1.492963e+08
           1978           NaN         7.050800e+04  1.543039e+08
           1979           NaN         7.055300e+04  1.594559e+08
           1980           NaN         7.030100e+04  1.646707e+08
           1981           NaN         6.975000e+04  1.699266e+08
           1982           NaN         6.895000e+04  1.752377e+08
           1983           NaN         6.795800e+04  1.806063e+08
           1984           NaN         6.686300e+04  1.860057e+08
           1985  9.745209e+06         6.574400e+04  1.915643e+08
           1986  1.002370e+07         6.460500e+04  1.972021e+08
           1987  1.028571e+07         6.348400e+04  2.028519e+08
           1988  1.054490e+07         6.253800e+04  2.085463e+08
           1989  1.082099e+07         6.196700e+04  2.142505e+08
...                       ...                  ...           ...
GDP        1986  6.684492e+09         2.458963e+08  2.890606e+11
           1987  6.684492e+09         2.864741e+08  3.129250e+11
           1988  6.684492e+09         3.386963e+08  3.074560e+11
           1989  1.002674e+10         3.734037e+08  3.221911e+11
           1990  1.002741e+10         3.915704e+08  4.460181e+11
           1991  1.451950e+10         4.103889e+08  4.388799e+11
           1992  1.034140e+10         4.237630e+08  4.703749e+11
           1993  1.011215e+10         4.565370e+08  4.756916e+11
           1994  1.042090e+10         5.000889e+08  4.866723e+11
           1995  4.967585e+09         4.941852e+08  5.228684e+11
           1996  7.526964e+09         5.410741e+08  5.773078e+11
           1997  7.649716e+09         5.798519e+08  6.123037e+11
           1998  6.445428e+09         6.200370e+08  5.905141e+11
           1999  6.152937e+09         6.518519e+08  6.431349e+11
           2000  9.129635e+09         7.838379e+08  7.339481e+11
           2001  8.936064e+09         7.737652e+08  7.221506e+11
           2002  1.249735e+10         8.025293e+08  7.279939e+11
           2003  1.418895e+10         8.399964e+08  8.218702e+11
           2004  1.964085e+10         8.983561e+08  9.639180e+11
           2005  2.823371e+10         9.973741e+08  1.184735e+12
           2006  4.178948e+10         1.135144e+09  1.404190e+12
           2007  6.044892e+10         1.289254e+09  1.641666e+12
           2008  8.417803e+10         1.347350e+09  2.081343e+12
           2009  7.549238e+10         1.206410e+09  1.798878e+12
           2010  8.247091e+10         1.135539e+09  2.103825e+12
           2011  1.041159e+11         1.129918e+09  2.497945e+12
           2012  1.153984e+11         1.204713e+09  2.773270e+12
           2013  1.249121e+11         1.200588e+09  2.846994e+12
           2014  1.267751e+11         1.220976e+09  2.873600e+12
           2015  1.026431e+11         1.297285e+09  2.530102e+12

country             Argentina       Armenia         Aruba      ...       \
           year                                                ...
Population 1960           NaN           NaN           NaN      ...
           1961           NaN           NaN           NaN      ...
           1962  2.128768e+07           NaN           NaN      ...
           1963  2.162184e+07           NaN           NaN      ...
           1964  2.195393e+07           NaN           NaN      ...
           1965  2.228339e+07           NaN           NaN      ...
           1966  2.260875e+07           NaN           NaN      ...
           1967  2.293220e+07           NaN           NaN      ...
           1968  2.326127e+07           NaN           NaN      ...
           1969  2.360599e+07           NaN           NaN      ...
           1970  2.397306e+07           NaN           NaN      ...
           1971  2.436644e+07           NaN           NaN      ...
           1972  2.478295e+07           NaN           NaN      ...
           1973  2.521339e+07           NaN           NaN      ...
           1974  2.564450e+07           NaN           NaN      ...
           1975  2.606698e+07           NaN           NaN      ...
           1976  2.647715e+07           NaN           NaN      ...
           1977  2.687857e+07           NaN           NaN      ...
           1978  2.727774e+07           NaN           NaN      ...
           1979  2.768453e+07           NaN           NaN      ...
           1980  2.810589e+07           NaN           NaN      ...
           1981  2.854337e+07           NaN           NaN      ...
           1982  2.899399e+07           NaN           NaN      ...
           1983  2.945474e+07           NaN           NaN      ...
           1984  2.992091e+07           NaN           NaN      ...
           1985  3.038878e+07           NaN           NaN      ...
           1986  3.085724e+07           NaN           NaN      ...
           1987  3.132647e+07           NaN           NaN      ...
           1988  3.179552e+07           NaN           NaN      ...
           1989  3.226356e+07           NaN           NaN      ...
...                       ...           ...           ...      ...
GDP        1986  1.109344e+11           NaN           NaN      ...
           1987  1.111062e+11           NaN           NaN      ...
           1988  1.262068e+11           NaN           NaN      ...
           1989  7.663690e+10           NaN           NaN      ...
           1990  1.413524e+11  2.256839e+09           NaN      ...
           1991  1.897200e+11  2.068527e+09           NaN      ...
           1992  2.287886e+11  1.272578e+09           NaN      ...
           1993  2.367417e+11  1.201313e+09           NaN      ...
           1994  2.574400e+11  1.315159e+09  1.330168e+09      ...
           1995  2.580318e+11  1.468317e+09  1.320670e+09      ...
           1996  2.721498e+11  1.596969e+09  1.379888e+09      ...
           1997  2.928590e+11  1.639492e+09  1.531844e+09      ...
           1998  2.989482e+11  1.893726e+09  1.665363e+09      ...
           1999  2.835230e+11  1.845482e+09  1.722799e+09      ...
           2000  2.842038e+11  1.911564e+09  1.873453e+09      ...
           2001  2.686968e+11  2.118468e+09  1.920263e+09      ...
           2002  9.772451e+10  2.376335e+09  1.941095e+09      ...
           2003  1.275863e+11  2.807061e+09  2.021302e+09      ...
           2004  1.818731e+11  3.576615e+09  2.228279e+09      ...
           2005  2.208138e+11  4.900470e+09  2.331006e+09      ...
           2006  2.626665e+11  6.384452e+09  2.421475e+09      ...
           2007  3.293175e+11  9.206302e+09  2.623726e+09      ...
           2008  4.037820e+11  1.166204e+10  2.791961e+09      ...
           2009  3.766279e+11  8.647937e+09  2.498933e+09      ...
           2010  4.616402e+11  9.260285e+09  2.467704e+09      ...
           2011  5.578902e+11  1.014211e+10  2.584464e+09      ...
           2012  6.043785e+11  1.061932e+10           NaN      ...
           2013  6.239320e+11  1.112147e+10           NaN      ...
           2014  5.480549e+11  1.164444e+10           NaN      ...
           2015           NaN  1.056140e+10           NaN      ...

country            Uzbekistan       Vanuatu  Venezuela, RB       Vietnam  \
           year
Population 1960           NaN           NaN   8.146845e+06           NaN
           1961           NaN           NaN   8.461684e+06           NaN
           1962           NaN           NaN   8.790590e+06           NaN
           1963           NaN           NaN   9.130346e+06           NaN
           1964           NaN           NaN   9.476255e+06           NaN
           1965           NaN           NaN   9.824694e+06           NaN
           1966           NaN           NaN   1.017514e+07           NaN
           1967           NaN           NaN   1.052805e+07           NaN
           1968           NaN           NaN   1.088200e+07           NaN
           1969           NaN           NaN   1.123549e+07           NaN
           1970           NaN           NaN   1.158776e+07           NaN
           1971           NaN           NaN   1.193780e+07           NaN
           1972           NaN           NaN   1.228643e+07           NaN
           1973           NaN           NaN   1.263697e+07           NaN
           1974           NaN           NaN   1.299402e+07           NaN
           1975           NaN           NaN   1.336099e+07           NaN
           1976           NaN           NaN   1.373914e+07           NaN
           1977           NaN           NaN   1.412779e+07           NaN
           1978           NaN           NaN   1.452593e+07           NaN
           1979           NaN  1.125790e+05   1.493174e+07           NaN
           1980           NaN  1.156340e+05   1.534392e+07           NaN
           1981           NaN  1.185780e+05   1.576180e+07           NaN
           1982           NaN  1.214330e+05   1.618590e+07           NaN
           1983           NaN  1.242480e+05   1.661734e+07           NaN
           1984           NaN  1.270940e+05   1.705779e+07           NaN
           1985           NaN  1.300280e+05   1.750806e+07  5.886800e+07
           1986           NaN  1.330400e+05   1.796853e+07  6.024900e+07
           1987           NaN  1.361290e+05   1.843774e+07  6.175000e+07
           1988           NaN  1.393690e+05   1.891243e+07  6.326300e+07
           1989           NaN  1.428520e+05   1.938826e+07  6.477400e+07
...                       ...           ...            ...           ...
GDP        1986           NaN  1.186914e+08   5.891511e+10  2.633662e+10
           1987           NaN  1.308341e+08   4.534379e+10  3.665811e+10
           1988           NaN  1.485454e+08   5.842840e+10  2.542381e+10
           1989           NaN  1.444822e+08   4.214230e+10  6.293305e+09
           1990  1.336061e+10  1.583974e+08   4.702751e+10  6.471740e+09
           1991  1.367762e+10  1.888700e+08   5.173436e+10  9.613370e+09
           1992  1.294130e+10  1.961426e+08   5.847036e+10  9.866990e+09
           1993  1.309901e+10  1.880804e+08   5.810756e+10  1.318095e+10
           1994  1.289916e+10  2.192603e+08   5.652990e+10  1.628643e+10
           1995  1.335047e+10  2.339021e+08   7.488874e+10  2.073616e+10
           1996  1.394889e+10  2.451776e+08   6.825859e+10  2.465747e+10
           1997  1.474460e+10  2.558902e+08   8.583739e+10  2.684370e+10
           1998  1.498897e+10  2.623013e+08   9.133854e+10  2.720960e+10
           1999  1.707847e+10  2.679992e+08   9.797414e+10  2.868366e+10
           2000  1.376037e+10  2.720147e+08   1.171476e+11  3.364009e+10
           2001  1.140135e+10  2.579269e+08   1.229097e+11  3.529135e+10
           2002  9.687951e+09  2.626038e+08   9.288959e+10  3.794790e+10
           2003  1.012811e+10  3.144631e+08   8.362219e+10  4.271707e+10
           2004  1.203002e+10  3.649969e+08   1.124514e+11  4.942411e+10
           2005  1.430751e+10  3.949626e+08   1.455135e+11  5.763326e+10
           2006  1.703090e+10  4.393768e+08   1.834775e+11  6.637166e+10
           2007  2.231139e+10  5.264283e+08   2.303642e+11  7.741443e+10
           2008  2.793403e+10  6.079586e+08   3.156002e+11  9.913030e+10
           2009  3.281683e+10  6.100666e+08   3.294190e+11  1.060146e+11
           2010  3.933277e+10  7.008043e+08   3.938015e+11  1.159317e+11
           2011  4.532432e+10  7.921497e+08   3.164822e+11  1.355395e+11
           2012  5.118344e+10  7.817029e+08   3.812862e+11  1.558200e+11
           2013  5.679566e+10  8.017876e+08   3.713366e+11  1.712220e+11
           2014  6.313285e+10  8.149546e+08            NaN  1.862047e+11
           2015  6.673280e+10           NaN            NaN  1.935994e+11

country          Virgin Islands (U.S.)  West Bank and Gaza         World  \
           year
Population 1960           3.200000e+04                 NaN  3.035056e+09
           1961           3.410000e+04                 NaN  3.076121e+09
           1962           3.630000e+04                 NaN  3.129064e+09
           1963           3.870000e+04                 NaN  3.193947e+09
           1964           4.130000e+04                 NaN  3.259355e+09
           1965           4.400000e+04                 NaN  3.326054e+09
           1966           4.730000e+04                 NaN  3.395866e+09
           1967           5.080000e+04                 NaN  3.465297e+09
           1968           5.460000e+04                 NaN  3.535512e+09
           1969           5.860000e+04                 NaN  3.609910e+09
           1970           6.300000e+04                 NaN  3.684997e+09
           1971           7.100000e+04                 NaN  3.762290e+09
           1972           7.600000e+04                 NaN  3.839016e+09
           1973           8.400000e+04                 NaN  3.914800e+09
           1974           9.000000e+04                 NaN  3.991194e+09
           1975           9.400000e+04                 NaN  4.065955e+09
           1976           9.600000e+04                 NaN  4.138731e+09
           1977           9.300000e+04                 NaN  4.211259e+09
           1978           9.600000e+04                 NaN  4.285062e+09
           1979           9.600000e+04                 NaN  4.360572e+09
           1980           9.700000e+04                 NaN  4.436735e+09
           1981           9.800000e+04                 NaN  4.514656e+09
           1982           1.020000e+05                 NaN  4.595488e+09
           1983           1.040000e+05                 NaN  4.677020e+09
           1984           1.080000e+05                 NaN  4.758310e+09
           1985           1.070000e+05                 NaN  4.841377e+09
           1986           1.065000e+05                 NaN  4.927207e+09
           1987           1.060000e+05                 NaN  5.015268e+09
           1988           1.045000e+05                 NaN  5.104205e+09
           1989           1.030000e+05                 NaN  5.193123e+09
...                                ...                 ...           ...
GDP        1986           1.035600e+09                 NaN  1.499712e+13
           1987           1.147800e+09                 NaN  1.706395e+13
           1988           1.204600e+09                 NaN  1.910918e+13
           1989           1.343900e+09                 NaN  2.006077e+13

In [60]:
s = world.stack()

In [64]:
s.unstack(-1)

                  Population           GDP
country     year
Afghanistan 1960   8994793.0  5.377778e+08
            1961   9164945.0  5.488889e+08
            1962   9343772.0  5.466667e+08
            1963   9531555.0  7.511112e+08
            1964   9728645.0  8.000000e+08
            1965   9935358.0  1.006667e+09
            1966  10148841.0  1.400000e+09
            1967  10368600.0  1.673333e+09
            1968  10599790.0  1.373333e+09
            1969  10849510.0  1.408889e+09
            1970  11121097.0  1.748887e+09
            1971  11412821.0  1.831109e+09
            1972  11716896.0  1.595555e+09
            1973  12022514.0  1.733333e+09
            1974  12315553.0  2.155555e+09
            1975  12582954.0  2.366667e+09
            1976  12831361.0  2.555556e+09
            1977  13056499.0  2.953333e+09
            1978  13222547.0  3.300000e+09
            1979  13283279.0  3.697940e+09
            1980  13211412.0  3.641723e+09
            1981  12996923.0  3.478788e+09
            2001  20531160.0  2.461666e+09
            2002  21487079.0  4.128818e+09
            2003  22507368.0  4.583649e+09
            2004  23499850.0  5.285462e+09
            2005  24399948.0  6.275076e+09
            2006  25183615.0  7.057598e+09
            2007  25877544.0  9.843842e+09
            2008  26528741.0  1.019053e+10
...                      ...           ...
Zimbabwe    1986   9198874.0  6.217524e+09
            1987   9535657.0  6.741215e+09
            1988   9866776.0  7.814784e+09
            1989  10184966.0  8.286323e+09
            1990  10484771.0  8.783817e+09
            1991  10763036.0  8.641482e+09
            1992  11019717.0  6.751472e+09
            1993  11256512.0  6.563813e+09
            1994  11476807.0  6.890675e+09
            1995  11683136.0  7.111271e+09
            1996  11877664.0  8.553147e+09
            1997  12059858.0  8.529572e+09
            1998  12226742.0  6.401968e+09
            1999  12374019.0  6.858013e+09
            2000  12499981.0  6.689958e+09
            2001  12603988.0  6.777385e+09
            2002  12691431.0  6.342116e+09
            2003  12774162.0  5.727592e+09
            2004  12867828.0  5.805598e+09
            2005  12984418.0  5.755215e+09
            2006  13127942.0  5.443896e+09
            2007  13297798.0  5.291950e+09
            2008  13495462.0  4.415703e+09
            2009  13720997.0  8.157077e+09
            2010  13973897.0  9.422161e+09
            2011  14255592.0  1.095623e+10
            2012  14565482.0  1.239272e+10
            2013  14898092.0  1.349023e+10
            2014  15245855.0  1.419691e+10
            2015  15602751.0  1.389294e+10

[11211 rows x 2 columns]

In [67]:
s.unstack(level=[0,1])

country       Arab World                                            \
year                2015          2014          2013          2012
Population  3.920223e+08  3.842226e+08  3.765043e+08  3.688026e+08
GDP         2.530102e+12  2.873600e+12  2.846994e+12  2.773270e+12

country                                                             \
year                2011          2010          2009          2008
Population  3.610318e+08  3.531122e+08  3.450542e+08  3.368865e+08
GDP         2.497945e+12  2.103825e+12  1.798878e+12  2.081343e+12

country                                     ...           Zimbabwe  \
year                2007          2006      ...               1969
Population  3.287666e+08  3.209067e+08      ...       5.036321e+06
GDP         1.641666e+12  1.404190e+12      ...       1.747999e+09

country                                                             \
year                1968          1967          1966          1965
Population  4.874113e+06  4.718612e+06  4.568320e+06  4.422132e+06
GDP         1.479600e+09  1.397002e+09  1.281750e+09  1.311436e+09

country                                                             \
year                1964          1963          1962          1961
Population  4.279561e+06  4.140804e+06  4.006262e+06  3.876638e+06
GDP         1.217138e+09  1.159512e+09  1.117602e+09  1.096647e+09

country
year                1960
Population  3.752390e+06
GDP         1.052990e+09

[2 rows x 11211 columns]

In [69]:
s.unstack("year", fill_value=0)

year                                      1960          1961          1962  \
country
Afghanistan           Population  8.994793e+06  9.164945e+06  9.343772e+06
                      GDP         5.377778e+08  5.488889e+08  5.466667e+08
Albania               Population  0.000000e+00  0.000000e+00  0.000000e+00
                      GDP         0.000000e+00  0.000000e+00  0.000000e+00
Algeria               Population  1.112489e+07  1.140486e+07  1.169015e+07
                      GDP         2.723638e+09  2.434767e+09  2.001461e+09
Andorra               Population  0.000000e+00  0.000000e+00  0.000000e+00
                      GDP         0.000000e+00  0.000000e+00  0.000000e+00
Angola                Population  0.000000e+00  0.000000e+00  0.000000e+00
                      GDP         0.000000e+00  0.000000e+00  0.000000e+00
Antigua and Barbuda   Population  0.000000e+00  0.000000e+00  0.000000e+00
                      GDP         0.000000e+00  0.000000e+00  0.000000e+00
Arab World            Population  0.000000e+00  0.000000e+00  0.000000e+00
                      GDP         0.000000e+00  0.000000e+00  0.000000e+00
Argentina             Population  0.000000e+00  0.000000e+00  2.128768e+07
                      GDP         0.000000e+00  0.000000e+00  2.445060e+10
Armenia               Population  0.000000e+00  0.000000e+00  0.000000e+00
                      GDP         0.000000e+00  0.000000e+00  0.000000e+00
Aruba                 Population  0.000000e+00  0.000000e+00  0.000000e+00
                      GDP         0.000000e+00  0.000000e+00  0.000000e+00
Australia             Population  1.027648e+07  1.048300e+07  1.074200e+07
                      GDP         1.856759e+10  1.963938e+10  1.988353e+10
Austria               Population  7.047539e+06  7.086299e+06  7.129864e+06
                      GDP         6.592694e+09  7.311750e+09  7.756110e+09
Azerbaijan            Population  0.000000e+00  0.000000e+00  0.000000e+00
                      GDP         0.000000e+00  0.000000e+00  0.000000e+00
Bahamas, The          Population  1.095260e+05  1.151080e+05  1.210830e+05
                      GDP         1.698023e+08  1.900962e+08  2.122528e+08
Bahrain               Population  0.000000e+00  0.000000e+00  0.000000e+00
                      GDP         0.000000e+00  0.000000e+00  0.000000e+00
...                                        ...           ...           ...
United Arab Emirates  Population  0.000000e+00  0.000000e+00  0.000000e+00
                      GDP         0.000000e+00  0.000000e+00  0.000000e+00
United Kingdom        Population  5.240000e+07  5.280000e+07  5.325000e+07
                      GDP         7.232805e+10  7.669436e+10  8.060194e+10
United States         Population  1.806710e+08  1.836910e+08  1.865380e+08
                      GDP         5.433000e+11  5.633000e+11  6.051000e+11
Upper middle income   Population  1.154592e+09  1.159145e+09  1.176093e+09
                      GDP         1.854612e+11  1.690732e+11  1.777957e+11
Uruguay               Population  2.538651e+06  2.571691e+06  2.603887e+06
                      GDP         1.242289e+09  1.547389e+09  1.710004e+09
Uzbekistan            Population  0.000000e+00  0.000000e+00  0.000000e+00
                      GDP         0.000000e+00  0.000000e+00  0.000000e+00
Vanuatu               Population  0.000000e+00  0.000000e+00  0.000000e+00
                      GDP         0.000000e+00  0.000000e+00  0.000000e+00
Venezuela, RB         Population  8.146845e+06  8.461684e+06  8.790590e+06
                      GDP         8.607600e+09  8.923367e+09  9.873398e+09
Vietnam               Population  0.000000e+00  0.000000e+00  0.000000e+00
                      GDP         0.000000e+00  0.000000e+00  0.000000e+00
Virgin Islands (U.S.) Population  3.200000e+04  3.410000e+04  3.630000e+04
                      GDP         2.420000e+07  2.570000e+07  3.690000e+07
West Bank and Gaza    Population  0.000000e+00  0.000000e+00  0.000000e+00
                      GDP         0.000000e+00  0.000000e+00  0.000000e+00
World                 Population  3.035056e+09  3.076121e+09  3.129064e+09
                      GDP         1.364643e+12  1.420440e+12  1.524573e+12
Yemen, Rep.           Population  0.000000e+00  0.000000e+00  0.000000e+00
                      GDP         0.000000e+00  0.000000e+00  0.000000e+00
Zambia                Population  3.049586e+06  3.142848e+06  3.240664e+06
                      GDP         6.987397e+08  6.823597e+08  6.792797e+08
Zimbabwe              Population  3.752390e+06  3.876638e+06  4.006262e+06
                      GDP         1.052990e+09  1.096647e+09  1.117602e+09

year                                      1963          1964          1965  \
country
Afghanistan           Population  9.531555e+06  9.728645e+06  9.935358e+06
                      GDP         7.511112e+08  8.000000e+08  1.006667e+09
Albania               Population  0.000000e+00  0.000000e+00  0.000000e+00
                      GDP         0.000000e+00  0.000000e+00  0.000000e+00
Algeria               Population  1.198513e+07  1.229597e+07  1.262695e+07
                      GDP         2.703004e+09  2.909340e+09  3.136284e+09
Andorra               Population  0.000000e+00  0.000000e+00  0.000000e+00
                      GDP         0.000000e+00  0.000000e+00  0.000000e+00
Angola                Population  0.000000e+00  0.000000e+00  0.000000e+00
                      GDP         0.000000e+00  0.000000e+00  0.000000e+00
Antigua and Barbuda   Population  0.000000e+00  0.000000e+00  0.000000e+00
                      GDP         0.000000e+00  0.000000e+00  0.000000e+00
Arab World            Population  0.000000e+00  0.000000e+00  0.000000e+00
                      GDP         0.000000e+00  0.000000e+00  0.000000e+00
Argentina             Population  2.162184e+07  2.195393e+07  2.228339e+07
                      GDP         1.827212e+10  2.560525e+10  2.834471e+10
Armenia               Population  0.000000e+00  0.000000e+00  0.000000e+00
                      GDP         0.000000e+00  0.000000e+00  0.000000e+00
Aruba                 Population  0.000000e+00  0.000000e+00  0.000000e+00
                      GDP         0.000000e+00  0.000000e+00  0.000000e+00
Australia             Population  1.095000e+07  1.116700e+07  1.138800e+07
                      GDP         2.149737e+10  2.375406e+10  2.592564e+10
Austria               Population  7.175811e+06  7.223801e+06  7.270889e+06
                      GDP         8.374175e+09  9.169984e+09  9.994071e+09
Azerbaijan            Population  0.000000e+00  0.000000e+00  0.000000e+00
                      GDP         0.000000e+00  0.000000e+00  0.000000e+00
Bahamas, The          Population  1.273310e+05  1.336970e+05  1.400490e+05
                      GDP         2.377428e+08  2.666641e+08  3.003922e+08
Bahrain               Population  0.000000e+00  0.000000e+00  0.000000e+00
                      GDP         0.000000e+00  0.000000e+00  0.000000e+00
...                                        ...           ...           ...
United Arab Emirates  Population  0.000000e+00  0.000000e+00  0.000000e+00
                      GDP         0.000000e+00  0.000000e+00  0.000000e+00
United Kingdom        Population  5.365000e+07  5.400000e+07  5.434805e+07
                      GDP         8.544377e+10  9.338760e+10  1.005958e+11
United States         Population  1.892420e+08  1.918890e+08  1.943030e+08
                      GDP         6.386000e+11  6.858000e+11  7.437000e+11
Upper middle income   Population  1.204372e+09  1.232266e+09  1.261069e+09
                      GDP         1.955819e+11  2.144250e+11  2.397244e+11
Uruguay               Population  2.635128e+06  2.665387e+06  2.694535e+06
                      GDP         1.539682e+09  1.975702e+09  1.890769e+09
Uzbekistan            Population  0.000000e+00  0.000000e+00  0.000000e+00
                      GDP         0.000000e+00  0.000000e+00  0.000000e+00
Vanuatu               Population  0.000000e+00  0.000000e+00  0.000000e+00
                      GDP         0.000000e+00  0.000000e+00  0.000000e+00
Venezuela, RB         Population  9.130346e+06  9.476255e+06  9.824694e+06
                      GDP         1.066338e+10  9.113581e+09  9.602945e+09
Vietnam               Population  0.000000e+00  0.000000e+00  0.000000e+00
                      GDP         0.000000e+00  0.000000e+00  0.000000e+00
Virgin Islands (U.S.) Population  3.870000e+04  4.130000e+04  4.400000e+04
                      GDP         4.140000e+07  5.380000e+07  6.650000e+07
West Bank and Gaza    Population  0.000000e+00  0.000000e+00  0.000000e+00
                      GDP         0.000000e+00  0.000000e+00  0.000000e+00
World                 Population  3.193947e+09  3.259355e+09  3.326054e+09
                      GDP         1.638187e+12  1.799675e+12  1.959900e+12
Yemen, Rep.           Population  0.000000e+00  0.000000e+00  0.000000e+00
                      GDP         0.000000e+00  0.000000e+00  0.000000e+00
Zambia                Population  3.342894e+06  3.449266e+06  3.559687e+06
                      GDP         7.043397e+08  8.226397e+08  1.061200e+09
Zimbabwe              Population  4.140804e+06  4.279561e+06  4.422132e+06
                      GDP         1.159512e+09  1.217138e+09  1.311436e+09

year                                      1966          1967          1968  \
country
Afghanistan           Population  1.014884e+07  1.036860e+07  1.059979e+07
                      GDP         1.400000e+09  1.673333e+09  1.373333e+09
Albania               Population  0.000000e+00  0.000000e+00  0.000000e+00
                      GDP         0.000000e+00  0.000000e+00  0.000000e+00
Algeria               Population  1.298027e+07  1.335420e+07  1.374438e+07
                      GDP         3.039859e+09  3.370870e+09  3.852147e+09
Andorra               Population  0.000000e+00  0.000000e+00  0.000000e+00
                      GDP         0.000000e+00  0.000000e+00  0.000000e+00
Angola                Population  0.000000e+00  0.000000e+00  0.000000e+00
                      GDP         0.000000e+00  0.000000e+00  0.000000e+00
Antigua and Barbuda   Population  0.000000e+00  0.000000e+00  0.000000e+00
                      GDP         0.000000e+00  0.000000e+00  0.000000e+00
Arab World            Population  0.000000e+00  0.000000e+00  1.155571e+08
                      GDP         0.000000e+00  0.000000e+00  2.552596e+10
Argentina             Population  2.260875e+07  2.293220e+07  2.326127e+07
                      GDP         2.863047e+10  2.425667e+10  2.643686e+10
Armenia               Population  0.000000e+00  0.000000e+00  0.000000e+00
                      GDP         0.000000e+00  0.000000e+00  0.000000e+00
Aruba                 Population  0.000000e+00  0.000000e+00  0.000000e+00
                      GDP         0.000000e+00  0.000000e+00  0.000000e+00
Australia             Population  1.165100e+07  1.179900e+07  1.200900e+07
                      GDP         2.725053e+10  3.037854e+10  3.264195e+10
Austria               Population  7.322066e+06  7.376998e+06  7.415403e+06
                      GDP         1.088768e+10  1.157943e+10  1.244063e+10
Azerbaijan            Population  0.000000e+00  0.000000e+00  0.000000e+00
                      GDP         0.000000e+00  0.000000e+00  0.000000e+00
Bahamas, The          Population  1.463640e+05  1.526070e+05  1.586290e+05
                      GDP         3.400000e+08  3.901961e+08  4.449020e+08
Bahrain               Population  0.000000e+00  0.000000e+00  0.000000e+00
                      GDP         0.000000e+00  0.000000e+00  0.000000e+00
...                                        ...           ...           ...
United Arab Emirates  Population  0.000000e+00  0.000000e+00  0.000000e+00
                      GDP         0.000000e+00  0.000000e+00  0.000000e+00
United Kingdom        Population  5.464850e+07  5.494360e+07  5.521170e+07
                      GDP         1.070907e+11  1.111854e+11  1.047027e+11
United States         Population  1.965600e+08  1.987120e+08  2.007060e+08
                      GDP         8.150000e+11  8.617000e+11  9.425000e+11
Upper middle income   Population  1.292755e+09  1.323615e+09  1.355381e+09
                      GDP         2.666625e+11  2.766866e+11  2.898954e+11
Uruguay               Population  2.722874e+06  2.750093e+06  2.774771e+06
                      GDP         1.809184e+09  1.597721e+09  1.593675e+09
Uzbekistan            Population  0.000000e+00  0.000000e+00  0.000000e+00
                      GDP         0.000000e+00  0.000000e+00  0.000000e+00
Vanuatu               Population  0.000000e+00  0.000000e+00  0.000000e+00
                      GDP         0.000000e+00  0.000000e+00  0.000000e+00
Venezuela, RB         Population  1.017514e+07  1.052805e+07  1.088200e+07
                      GDP         1.009657e+10  1.047278e+10  1.147091e+10
Vietnam               Population  0.000000e+00  0.000000e+00  0.000000e+00
                      GDP         0.000000e+00  0.000000e+00  0.000000e+00
Virgin Islands (U.S.) Population  4.730000e+04  5.080000e+04  5.460000e+04
                      GDP         8.410000e+07  1.154000e+08  1.738000e+08
West Bank and Gaza    Population  0.000000e+00  0.000000e+00  0.000000e+00
                      GDP         0.000000e+00  0.000000e+00  0.000000e+00
World                 Population  3.395866e+09  3.465297e+09  3.535512e+09
                      GDP         2.125397e+12  2.262923e+12  2.440549e+12
Yemen, Rep.           Population  0.000000e+00  0.000000e+00  0.000000e+00
                      GDP         0.000000e+00  0.000000e+00  0.000000e+00
Zambia                Population  3.674088e+06  3.792864e+06  3.916928e+06
                      GDP         1.239000e+09  1.340639e+09  1.573739e+09
Zimbabwe              Population  4.568320e+06  4.718612e+06  4.874113e+06
                      GDP         1.281750e+09  1.397002e+09  1.479600e+09

year                                      1969      ...               2006  \
country                                             ...
Afghanistan           Population  1.084951e+07      ...       2.518362e+07
                      GDP         1.408889e+09      ...       7.057598e+09
Albania               Population  0.000000e+00      ...       2.992547e+06
                      GDP         0.000000e+00      ...       8.992642e+09
Algeria               Population  1.414444e+07      ...       3.374933e+07
                      GDP         4.257253e+09      ...       1.170273e+11
Andorra               Population  0.000000e+00      ...       8.337300e+04
                      GDP         0.000000e+00      ...       3.536452e+09
Angola                Population  0.000000e+00      ...       1.854147e+07
                      GDP         0.000000e+00      ...       4.178948e+10
Antigua and Barbuda   Population  0.000000e+00      ...       8.346700e+04
                      GDP         0.000000e+00      ...       1.135144e+09
Arab World            Population  1.188239e+08      ...       3.209067e+08
                      GDP         2.817577e+10      ...       1.404190e+12
Argentina             Population  2.360599e+07      ...       3.955875e+07
                      GDP         3.125628e+10      ...       2.626665e+11
Armenia               Population  0.000000e+00      ...       3.002161e+06
                      GDP         0.000000e+00      ...       6.384452e+09
Aruba                 Population  0.000000e+00      ...       1.008300e+05
                      GDP         0.000000e+00      ...       2.421475e+09
Australia             Population  1.226300e+07      ...       2.069790e+07
                      GDP         3.660656e+10      ...       7.468808e+11
Austria               Population  7.441055e+06      ...       8.268641e+06
                      GDP         1.358280e+10      ...       3.343094e+11
Azerbaijan            Population  0.000000e+00      ...       8.484550e+06
                      GDP         0.000000e+00      ...       2.098302e+10
Bahamas, The          Population  1.642500e+05      ...       3.358010e+05
                      GDP         5.281373e+08      ...       7.965588e+09
Bahrain               Population  0.000000e+00      ...       9.408080e+05
                      GDP         0.000000e+00      ...       1.850505e+10
...                                        ...      ...                ...
United Arab Emirates  Population  0.000000e+00      ...       5.171255e+06
                      GDP         0.000000e+00      ...       2.221059e+11
United Kingdom        Population  5.544175e+07      ...       6.084682e+07
                      GDP         1.126769e+11      ...       2.588077e+12
United States         Population  2.026770e+08      ...       2.983799e+08
                      GDP         1.019900e+12      ...       1.385589e+13
Upper middle income   Population  1.388827e+09      ...       2.380136e+09
                      GDP         3.221882e+11      ...       8.620784e+12
Uruguay               Population  2.795044e+06      ...       3.331041e+06
                      GDP         2.004435e+09      ...       1.957946e+10
Uzbekistan            Population  0.000000e+00      ...       2.648825e+07
                      GDP         0.000000e+00      ...       1.703090e+10
Vanuatu               Population  0.000000e+00      ...       2.146350e+05
                      GDP         0.000000e+00      ...       4.393768e+08
Venezuela, RB         Population  1.123549e+07      ...       2.722123e+07
                      GDP         1.192757e+10      ...       1.834775e+11
Vietnam               Population  0.000000e+00      ...       8.331120e+07
                      GDP         0.000000e+00      ...       6.637166e+10
Virgin Islands (U.S.) Population  5.860000e+04      ...       0.000000e+00
                      GDP         2.113000e+08      ...       0.000000e+00
West Bank and Gaza    Population  0.000000e+00      ...       3.406334e+06
                      GDP         0.000000e+00      ...       4.910100e+09
World                 Population  3.609910e+09      ...       6.594722e+09
                      GDP         2.686747e+12      ...       5.107451e+13
Yemen, Rep.           Population  0.000000e+00      ...       2.109397e+07
                      GDP         0.000000e+00      ...       1.908173e+10
Zambia                Population  4.047479e+06      ...       1.238151e+07
                      GDP         1.926399e+09      ...       1.275686e+10
Zimbabwe              Population  5.036321e+06      ...       1.312794e+07
                      GDP         1.747999e+09      ...       5.443896e+09

year                                      2007          2008          2009  \
country
Afghanistan           Population  2.587754e+07  2.652874e+07  2.720729e+07
                      GDP         9.843842e+09  1.019053e+10  1.248694e+10
Albania               Population  2.970017e+06  2.947314e+06  2.927519e+06
                      GDP         1.070101e+10  1.288135e+10  1.204421e+10
Algeria               Population  3.426197e+07  3.481106e+07  3.540179e+07
                      GDP         1.349771e+11  1.710007e+11  1.372110e+11
Andorra               Population  8.487800e+04  8.561600e+04  8.547400e+04
                      GDP         4.010785e+09  4.001349e+09  3.649863e+09
Angola                Population  1.918391e+07  1.984225e+07  2.052010e+07
                      GDP         6.044892e+10  8.417803e+10  7.549238e+10
Antigua and Barbuda   Population  8.439700e+04  8.535000e+04  8.630000e+04
                      GDP         1.289254e+09  1.347350e+09  1.206410e+09
Arab World            Population  3.287666e+08  3.368865e+08  3.450542e+08
                      GDP         1.641666e+12  2.081343e+12  1.798878e+12
Argentina             Population  3.996990e+07  4.038186e+07  4.079864e+07
                      GDP         3.293175e+11  4.037820e+11  3.766279e+11

In [76]:
sales=pd.read_csv("files/salesmen.csv", parse_dates=["Date"])
sales["Salesman"] = sales["Salesman"].astype("category")

In [77]:
sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1830 entries, 0 to 1829
Data columns (total 3 columns):
Date        1830 non-null datetime64[ns]
Salesman    1830 non-null category
Revenue     1830 non-null int64
dtypes: category(1), datetime64[ns](1), int64(1)
memory usage: 30.7 KB

In [81]:
sales.pivot(index="Date", columns="Salesman", values="Revenue")

366

In [86]:
foods = pd.read_csv("files/foods.csv")
foods.head(3)

  First Name  Gender      City Frequency     Item  Spend
0      Wanda  Female  Stamford    Weekly   Burger  15.66
1       Eric    Male  Stamford     Daily  Chalupa  10.56
2    Charles    Male  New York     Never    Sushi  42.14

In [89]:
foods.pivot_table(values="Spend", index="Gender", aggfunc="sum")

           Spend
Gender
Female  25963.33
Male    24106.04